### ISSUE TITLE
Update the instructions

### ISSUE THREAD

**Issue by jabley** [alphagov/publisher#182]
The README says that *These instructions are out of date. Updates coming soon*

@jystewart [wrote that over 2 years ago](https://github.com/alphagov/publisher/commit/182ec33112412b1b67eacf4ccc938c849d5a362e). Can we update the README with appropriate instructions please, or remove the suggestion that we will be providing updates soon?

**Comment by issyl0** [comment]
Just noticed this issue still hanging around. The wording was removed in https://github.com/alphagov/publisher/commit/fb08aa077159b1056130fa7d6bafa8d09a3a5247 just over a year ago.
